// Generated by CoffeeScript 1.7.1

/*
devis.js - pour school phenomenon
@author: Ophir LOJKINE
 */

(function() {
  var conf, date_livraison_min, gestion_nbr_articles, html_id, maj_prix, selection_nbr;

  selection_nbr = function(liste, nbr, greater) {
    var obj, _i, _len, _ref;
    _ref = (greater ? -1 : 1);
    for ((_ref > 0 ? (_i = 0, _len = liste.length) : _i = liste.length - 1); _ref > 0 ? _i < _len : _i >= 0; _i += _ref) {
      obj = liste[_i];
      if ((!greater && nbr < obj.nbr) || (greater && nbr >= obj.nbr)) {
        return obj;
      }
    }
    return null;
  };

  html_id = function(str) {
    return str.replace(RegExp(" ", "g"), "_");
  };

  maj_prix = function() {
    var $prix, $prix_varie, ajout_prix, article, input_id, nbr, perso, prix_obj, prix_perso_obj, prix_str, prix_total, _i, _j, _len, _len1, _ref, _ref1;
    prix_total = {
      prix: 0,
      approx: false
    };
    ajout_prix = function(p1, p2) {
      p1.prix += p2.prix | 0;
      return p1.approx = !!(p1.approx || p2.approx);
    };
    _ref = conf.liste_articles;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      article = _ref[_i];
      nbr = $("#" + article.id + "-nbr").val() | 0;
      $prix = $("#prix-unite-" + article.id);
      $prix_varie = $("#prix-varie-" + article.id).addClass("hidden");
      prix_obj = $.extend({}, selection_nbr(article.prix, nbr, true));
      if (prix_obj === null) {
        continue;
      }
      _ref1 = conf.personnalisations;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        perso = _ref1[_j];
        input_id = html_id("perso-" + article.id + "-" + perso.perso);
        if ($("#" + input_id).is(":checked")) {
          prix_perso_obj = selection_nbr(perso.prix, nbr, true);
          if (prix_perso_obj && prix_perso_obj.prix) {
            ajout_prix(prix_obj, prix_perso_obj);
          }
        }
      }
      prix_str = prix_obj.prix + conf.devise;
      if (prix_obj.approx) {
        prix_str = "environ " + prix_str;
        $prix_varie.removeClass("hidden");
      }
      $prix.text(prix_str);
      prix_obj.prix *= nbr;
      ajout_prix(prix_total, prix_obj);
    }
    $("#prix-total").text(prix_total.prix);
    $("#prix-total-varie").toggle(prix_total.approx);
    return prix_total;
  };

  $("#association").tooltip();

  $("#date-naissance input").on("blur change keyup", function() {
    var a, action, date_dixhuitans, j, m;
    j = parseInt($("#date-naissance-jour").val());
    m = parseInt($("#date-naissance-mois").val());
    a = parseInt($("#date-naissance-annee").val());
    if (j && m && a) {
      date_dixhuitans = new Date(a + 18, m - 1, j);
      action = (date_dixhuitans > (new Date()) ? "show" : "hide");
      return $("#alerte-age")[action](500);
    }
  });

  date_livraison_min = new Date();

  $("#date-livraison").datepicker({
    format: "dd/mm/yyyy",
    onRender: function(date) {
      if (date < date_livraison_min) {
        return "disabled";
      } else {
        return "";
      }
    }
  });

  $(".article-nbr").on("change mouseup keyup blur", maj_prix);

  $(".checkbox-perso").on("change mouseup keyup blur", maj_prix);

  gestion_nbr_articles = function(article) {
    var $btn, $nbrInput, id, nbr;
    id = article.id;
    $nbrInput = $("#" + id + "-nbr");
    nbr = parseInt($nbrInput.val()) || 0;
    $btn = $("#personnaliser-" + id);
    if (nbr === 0) {
      $nbrInput.parent().removeClass("has-error").removeClass("has-success");
      $nbrInput.tooltip("hide");
      return $btn.attr("disabled", true);
    } else if (nbr >= $nbrInput.attr("min")) {
      $nbrInput.parent().removeClass("has-error").addClass("has-success");
      $nbrInput.tooltip("hide");
      return $btn.attr("disabled", false);
    } else {
      $nbrInput.parent().addClass("has-error").removeClass("has-success");
      $nbrInput.tooltip("show");
      return $btn.attr("disabled", true);
    }
  };

  conf = {};

  $.ajax({
    url: "config/articles.json",
    dataType: "json",
    success: function(config) {
      var $nbrInput, $preview, article, couleur, liste_articles, min, nuance, nuancier, num, _i, _j, _len, _len1, _results;
      conf = config;
      nuancier = conf.nuancier;
      liste_articles = conf.liste_articles;
      for (_i = 0, _len = nuancier.length; _i < _len; _i++) {
        nuance = nuancier[_i];
        num = nuance.num;
        couleur = nuance.couleur;
        $preview = $("<div>").css("background-color", couleur).data("num", num);
        if (nuance.motif) {
          $preview.css("background-image", "url(images/motifs/" + num + ".jpg)");
        }
        $preview.click(function() {
          var $this, color;
          $this = $(this);
          color = $this.css("background-color");
          return $($this.parent().data("target")).val($this.data("num")).css({
            "background-image": $this.css("background-image"),
            "background-color": color,
            color: color
          }).on("change keyup", function() {
            return $(this).css({
              "background-image": "",
              "background-color": "",
              color: ""
            });
          });
        });
        $(".dropdown-colors").each(function() {
          $(this).append($preview.clone(true));
        });
      }
      _results = [];
      for (_j = 0, _len1 = liste_articles.length; _j < _len1; _j++) {
        article = liste_articles[_j];
        min = article.nbr_min || conf.commande_nbr_min;
        _results.push($nbrInput = $("#" + article.id + "-nbr").data("article-id", article.id).attr("min", min).attr("title", "Impossible de passer une commande de moins de " + min + " articles.").on('change focus blur keyup mouseup', function() {
          return gestion_nbr_articles(article);
        }).on("change focus blur mouseup", article, function(event) {
          var $this, article_id, choix_couleur, couleurs, div, divs, dropdown, group, nbr, restriction, restrictions, _k, _len2, _ref, _results1;
          $this = $(this);
          nbr = parseInt($this.val()) || 0;
          article = event.data;
          article_id = article.id;
          _ref = article.choix_couleurs;
          _results1 = [];
          for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
            choix_couleur = _ref[_k];
            restrictions = choix_couleur.restriction_couleurs || [];
            couleurs = null;
            restriction = selection_nbr(restrictions, nbr);
            dropdown = $("#dropdown-colors-" + choix_couleur.type_couleur + "-" + article_id);
            group = dropdown.parent(".choose-color").show();
            divs = dropdown.find("div").show();
            if (restriction === null) {
              continue;
            }
            couleurs = restriction.couleurs;
            if (couleurs.length === 0) {
              group.find("input").val("").trigger("change");
              _results1.push(group.hide());
            } else {
              _results1.push((function() {
                var _l, _len3, _results2;
                _results2 = [];
                for (_l = 0, _len3 = divs.length; _l < _len3; _l++) {
                  div = divs[_l];
                  div = $(div);
                  num = div.data("num") + "";
                  if (couleurs.indexOf(num) === -1) {
                    _results2.push(div.hide());
                  } else {
                    _results2.push(void 0);
                  }
                }
                return _results2;
              })());
            }
          }
          return _results1;
        }));
      }
      return _results;
    },
    error: function(xhr, status, e) {
      alert("Impossible de charger le nuancier.");
      console.log(status, e);
    }
  });

}).call(this);

//# sourceMappingURL=devis.map
